### ISSUE TITLE
Throw interpetable exception if file is not correctly parsed , i.e. it's not a tiff or siff file

### ISSUE THREAD

**Issue by MaximilianHoffmann** [MaimonLab/SiffPy#9]
Maybe throw a value error with a more interpretable error message when parsing already fails for the TIFF header.

**Comment by StephenThornquist** [comment]
This has now been changed. If you build `corrosiff-python` from the source repository (after installing `cargo`) instead of `PiPy`, or wait for the next release, you will get the error:
`OSError: File format error -- invalid or incompletely-transferred siff file` if you try to open an invalid file
